### PR TITLE
Action for slow tests

### PR DESCRIPTION
**Pull request by palewire**
This new workflow will run the slow and web tests when:
1. A pull request is submitted
2. Once per week on a cron
3. You manually click a button here on GitHub

### CODE REVIEW

**Comment by palewire** [comment]
As we might have predicted, the slow tests are failing here on GitHub. A quick look at [the logs](https://github.com/biglocalnews/court-scraper/pull/143/checks?check_run_id=3345163764) suggest that some of the necessary configuration files are not found in the bare repo.

I think this presents a practical case for considering how secrets might be included here in the GitHub environment in a way that works gracefully with the configuration system you've already established. When you have a second, give the errors a look and let me know if you have a take on how that might best be implemented. I'm happy to implement whatever approach you'd prefer, or freestyle on my own if that's easier.

**Comment by zstumgoren** [comment]
@palewire Yep, the "slow" tests present a few different problems that we may want to address separately. These tests are generally Selenium-based across the board. Some of them require login credentials and/or CAPTCHA handling. I think we could devise a system where login-based tests could be run automatically when PRs are submitted, but I'd like to prevent CAPTCHA-based tests from running automatically because we need to pay a third-party service to handle those. 

One possible solution that could get us closer to full test-coverage on CI could be the following:

1. Add a `captcha` pytest marker to any captcha-based tests and do not run them on CI
2. For non-CAPTCHA login tests, we might be able to get away with a simple user/pass env var lookup  such as `COURT_SCRAPER_LOGIN_USER` and `COURT_SCRAPER_LOGIN_PASS`. The only hitch there is that it requires us to use the same user/pass for all sites, which may or may not be possible depending on factors out of our control (e.g. password length/complexity requirements). A more complex alternative would be to check for env var-based creds in a way that allows for customization by place ID (basically mirroring the approach of config.yaml). For example, `COURT_SCRAPER_GA_DEKALB_USER` and `COURT_SCRAPER_GA_DEKALB_PASS`, if set, could take precedence over values found in the config.yaml file. I'm open to starting with the simple approach, and then pivoting to something more complex if the need arises. I believe either approach will likely require updates in `court_scraper.config` as well as in the Odyssey platform scraper (and perhaps elsewhere).

@palewire Let me know what you think, especially if you have ideas on a cleaner solution than (2).

**Comment by palewire** [comment]
Breaking the challenge into pieces sounds like a good plan to me. Next time I have a minute, I'll see if i can separate out the CAPTCHA tests. When we can look at the next challenge.

**Comment by zstumgoren** [comment]
> Breaking the challenge into pieces sounds like a good plan to me. Next time I have a minute, I'll see if i can separate out the CAPTCHA tests. Then we can look at the next challenge.

Sounds good. If it helps, you can pinpoint the tests that likely need a new pytest `captcha` marker by grepping the tests dir as follows: `grep -r "@pytest.mark.slow" tests`. From there, it may require running individual tests modules to see which sites require logins and/or captchas. For example, if memory serves, Chatham and Dekalb Counties in GA have logins but no captchas, while WI has captchas but no login requirements. 

You can add new pytest markers and associated CLI flags in `tests/conftest.py`.

Give a shout if you have questions along the way and many thanks for helping on this front!!

**Comment by palewire** [comment]
Copy. If we stick with this little initiative we should be able to come up with a strong testing foundation for your project. Then it'll be ready to grow!

**Comment by zstumgoren** [comment]
> I've merged in the results of #147 and #151, which allowed me to revise the test commands being run by the pull request action to only run those that do not require captcha. We still need to solve #149 before this can be considered for a merge, but it's progress.

@palewire Awesome! You're rocking and rolling! I'm still available through Tuesday for a merge (then gone for a week). But no pressure. Really appreciate all the work helping us get this over the finish line!

**Comment by palewire** [comment]
I am withdrawing this stale PR.

**Pull request closed without merging**
